# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veranstaltung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('art', models.CharField(choices=[('fest', 'Fest / Feier'), ('versammlung', 'Versammlung'), ('sitzung', 'Sitzung'), ('ausflug', 'Ausflug'), ('schulung', 'Übung / Schulung'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=12, verbose_name='Art')),
                ('status', models.CharField(choices=[('idee', 'Idee'), ('geplant', 'Geplant'), ('bestaetigt', 'Bestätigt'), ('abgesagt', 'Abgesagt'), ('abgeschlossen', 'Abgeschlossen')], default='geplant', max_length=14, verbose_name='Status')),
                ('beginn', models.DateTimeField(verbose_name='Beginn')),
                ('ende', models.DateTimeField(blank=True, null=True, verbose_name='Ende')),
                ('ort', models.CharField(blank=True, max_length=200, verbose_name='Ort')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erwartete_teilnehmer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Erwartete Teilnehmer')),
                ('oeffentlich', models.BooleanField(default=False, verbose_name='Öffentliche Veranstaltung')),
                ('anmeldung_erforderlich', models.BooleanField(default=False, verbose_name='Anmeldung erforderlich')),
                ('anmeldeschluss', models.DateField(blank=True, null=True, verbose_name='Anmeldeschluss')),
                ('notizen', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('openslides_meeting_id', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='OpenSlides-Meeting-ID')),
                ('verantwortlich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.mitglied', verbose_name='Verantwortlich')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'ordering': ['-beginn'],
            },
        ),
        migrations.CreateModel(
            name='Tagesordnungspunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('titel', models.CharField(max_length=250, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung / Beschlussvorlage')),
                ('openslides_topic_id', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='OpenSlides-Themen-ID')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesordnung', to='events.veranstaltung', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Tagesordnungspunkt',
                'verbose_name_plural': 'Tagesordnung',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Schicht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('bezeichnung', models.CharField(max_length=150, verbose_name='Bezeichnung')),
                ('beginn', models.DateTimeField(verbose_name='Beginn')),
                ('ende', models.DateTimeField(verbose_name='Ende')),
                ('benoetigt', models.PositiveIntegerField(default=1, verbose_name='Benötigte Helfer')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schichten', to='events.veranstaltung', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Schicht',
                'verbose_name_plural': 'Schichten',
                'ordering': ['beginn'],
            },
        ),
        migrations.CreateModel(
            name='Kostenposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('art', models.CharField(choices=[('einnahme', 'Einnahme'), ('ausgabe', 'Ausgabe')], default='ausgabe', max_length=8, verbose_name='Art')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('plan_betrag', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Geplant (€)')),
                ('ist_betrag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tatsächlich (€)')),
                ('beleg', models.FileField(blank=True, upload_to=apps.core.util.upload_pfad, verbose_name='Beleg')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kosten', to='events.veranstaltung', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Kostenposition',
                'verbose_name_plural': 'Kostenpositionen',
                'ordering': ['art', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=200, verbose_name='Aufgabe')),
                ('faellig', models.DateField(blank=True, null=True, verbose_name='Fällig bis')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('arbeit', 'In Arbeit'), ('erledigt', 'Erledigt')], default='offen', max_length=10, verbose_name='Status')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('zustaendig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.mitglied', verbose_name='Zuständig')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='events.veranstaltung', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['faellig', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Anmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name (Gast)')),
                ('personen', models.PositiveIntegerField(default=1, verbose_name='Anzahl Personen')),
                ('status', models.CharField(choices=[('zugesagt', 'Zugesagt'), ('offen', 'Offen'), ('abgesagt', 'Abgesagt')], default='zugesagt', max_length=10, verbose_name='Status')),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('mitglied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.mitglied', verbose_name='Mitglied')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='events.veranstaltung', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Anmeldung',
                'verbose_name_plural': 'Anmeldungen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Schichteinsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='members.mitglied', verbose_name='Helfer')),
                ('schicht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einsaetze', to='events.schicht', verbose_name='Schicht')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Schichteinsatz',
                'verbose_name_plural': 'Schichteinsätze',
                'unique_together': {('schicht', 'mitglied')},
            },
        ),
    ]
