# Generated by Django 6.1.1 on 2026-09-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemeinstellung'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wahlergebnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('amt', models.CharField(max_length=250, verbose_name='Amt / Wahl')),
                ('wahlgang', models.CharField(blank=True, max_length=250, verbose_name='Wahlgang')),
                ('ergebnis', models.TextField(verbose_name='Stimmenverteilung')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wahlergebnisse', to='events.veranstaltung', verbose_name='Veranstaltung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Wahlergebnis',
                'verbose_name_plural': 'Wahlergebnisse',
                'ordering': ['amt', 'wahlgang', 'id'],
            },
        ),
    ]
