# Generated by Django 6.1.2 on 2026-10-09 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_veranstaltung_rueckmeldung_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='benachrichtigt_am',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Überfälligkeits-Benachrichtigung verschickt am'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='veranstaltung',
            field=models.ForeignKey(blank=True, help_text='Optional - leer lassen für eine eigenständige Aufgabe ohne Bezug zu einer Veranstaltung/Sitzung.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben', to='events.veranstaltung', verbose_name='Veranstaltung'),
        ),
    ]
