# Generated by Django 6.1.2 on 2026-10-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_verein_aufgaben_geprueft_am'),
        ('events', '0006_aufgabe_benachrichtigt_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='ergebnis',
            field=models.TextField(blank=True, help_text='Kurzes Fazit beim Abschließen - was wurde erreicht/entschieden.', verbose_name='Ergebnis'),
        ),
        migrations.CreateModel(
            name='AufgabeNotiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Notiz')),
                ('erstellt_von', models.CharField(blank=True, editable=False, max_length=150, verbose_name='Von')),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notizen', to='events.aufgabe', verbose_name='Aufgabe')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Zwischennotiz',
                'verbose_name_plural': 'Zwischennotizen',
                'ordering': ['erstellt', 'id'],
            },
        ),
    ]
