# Generated by Django 6.1.2 on 2026-10-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_aufgabe_ergebnis_aufgabenotiz'),
        ('members', '0007_vorstand_funktion_pro_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='zustaendig_benutzer',
            field=models.ForeignKey(blank=True, help_text="Für Zuständige ohne Mitgliedschaft (z. B. externe Kassenprüfung) - nur zusammen mit 'Zuständig (Mitglied)' leer lassen, nicht beides gleichzeitig befüllen.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Zuständig (Administrator)'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='zustaendig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.mitglied', verbose_name='Zuständig (Mitglied)'),
        ),
    ]
