# Generated by Django 6.1.2 on 2026-10-09 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_aufgabe_zustaendig_benutzer_alter_aufgabe_zustaendig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='beobachter',
            field=models.ManyToManyField(blank=True, help_text="Erhalten eine E-Mail, sobald sich an dieser Aufgabe etwas ändert (Status, Ergebnis, Fälligkeit o. ä.) oder eine neue Zwischennotiz hinzukommt - unabhängig von 'Zuständig'.", related_name='beobachtete_aufgaben', to=settings.AUTH_USER_MODEL, verbose_name='Beobachter'),
        ),
    ]
