# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.fields
import apps.core.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Familie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Familienname / Bezeichnung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Familie',
                'verbose_name_plural': 'Familien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Funktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Funktion',
                'verbose_name_plural': 'Funktionen',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('mitgliedsnummer', models.PositiveIntegerField(blank=True, help_text='Leer lassen = automatisch vergeben', null=True, verbose_name='Mitgliedsnummer')),
                ('anrede', models.CharField(blank=True, choices=[('herr', 'Herr'), ('frau', 'Frau'), ('divers', 'Divers'), ('firma', 'Firma / Organisation')], max_length=10, verbose_name='Anrede')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('geburtsdatum', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('eintrittsdatum', models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum')),
                ('austrittsdatum', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('ruhend', 'Ruhend'), ('ausgetreten', 'Ausgetreten'), ('verstorben', 'Verstorben')], default='aktiv', max_length=12, verbose_name='Status')),
                ('ist_familienzahler', models.BooleanField(default=False, verbose_name='Zahlt den Familienbeitrag')),
                ('individueller_beitrag', models.DecimalField(blank=True, decimal_places=2, help_text='Überschreibt alle Beitragsregeln (0 = beitragsfrei)', max_digits=8, null=True, verbose_name='Individueller Jahresbeitrag (€)')),
                ('strasse', models.CharField(blank=True, max_length=200, verbose_name='Straße / Nr.')),
                ('plz', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('mobil', models.CharField(blank=True, max_length=40, verbose_name='Mobil')),
                ('zahlungsart', models.CharField(choices=[('ueberweisung', 'Überweisung'), ('lastschrift', 'SEPA-Lastschrift'), ('bar', 'Bar')], default='ueberweisung', max_length=12, verbose_name='Zahlungsart')),
                ('kontoinhaber', models.CharField(blank=True, max_length=150, verbose_name='Kontoinhaber')),
                ('iban', apps.core.fields.VerschluesseltesTextField(blank=True, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('mandatsreferenz', models.CharField(blank=True, max_length=35, verbose_name='SEPA-Mandatsreferenz')),
                ('mandatsdatum', models.DateField(blank=True, null=True, verbose_name='Datum des SEPA-Mandats')),
                ('foto', models.ImageField(blank=True, upload_to=apps.core.util.upload_pfad, verbose_name='Foto')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('openslides_user_id', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='OpenSlides-Konto-ID')),
                ('openslides_username', models.CharField(blank=True, editable=False, max_length=150, verbose_name='OpenSlides-Benutzername')),
                ('openslides_initialpasswort', apps.core.fields.VerschluesseltesTextField(blank=True, editable=False, verbose_name='OpenSlides-Startpasswort')),
                ('abteilungen', models.ManyToManyField(blank=True, to='members.abteilung', verbose_name='Abteilungen')),
                ('familie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.familie', verbose_name='Familie')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('kategorie', models.CharField(choices=[('beitritt', 'Beitrittserklärung'), ('sepa', 'SEPA-Mandat'), ('ehrung', 'Ehrung'), ('kuendigung', 'Kündigung'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=12, verbose_name='Kategorie')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('datei', models.FileField(upload_to=apps.core.util.upload_pfad, verbose_name='Datei')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='Version')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='members.mitglied', verbose_name='Mitglied')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-erstellt'],
            },
        ),
        migrations.CreateModel(
            name='MitgliedFunktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('von', models.DateField(blank=True, null=True, verbose_name='Von')),
                ('bis', models.DateField(blank=True, null=True, verbose_name='Bis')),
                ('funktion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.funktion', verbose_name='Funktion')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funktionen', to='members.mitglied', verbose_name='Mitglied')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Funktion eines Mitglieds',
                'verbose_name_plural': 'Funktionen der Mitglieder',
                'ordering': ['-von'],
            },
        ),
        migrations.CreateModel(
            name='Mitgliedsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('jahresbeitrag', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Standard-Jahresbeitrag (€)')),
                ('beschreibung', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Mitgliedsart',
                'verbose_name_plural': 'Mitgliedsarten / Beiträge',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mitglied',
            name='mitgliedsart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.mitgliedsart', verbose_name='Mitgliedsart'),
        ),
        migrations.AlterUniqueTogether(
            name='mitglied',
            unique_together={('verein', 'mitgliedsnummer')},
        ),
    ]
