# Generated by Django 6.1.1 on 2026-09-21 16:04

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='benutzer',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitglied_zugang', to=settings.AUTH_USER_MODEL, verbose_name='Zugang (Selbstdatenpflege)'),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='selbstdienst_initialpasswort',
            field=apps.core.fields.VerschluesseltesTextField(blank=True, editable=False, verbose_name='Selbstdienst-Startpasswort'),
        ),
    ]
