# Generated by Django 6.1.1 on 2026-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_mitglied_benutzer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='alters_ehrenabteilung',
            field=models.BooleanField(default=False, verbose_name='Alters- und Ehrenabteilung'),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='einsatzabteilung_aktiv',
            field=models.BooleanField(default=False, verbose_name='Aktives Mitglied der Einsatzabteilung'),
        ),
        migrations.AddField(
            model_name='mitglied',
            name='vorstandsmitglied',
            field=models.BooleanField(default=False, help_text='Setzt automatisch die Funktion „Vorstandsmitglied“. Nur Vorstandsmitglieder können mit Paperless abgeglichen werden (Verwaltung › Paperless-Anbindung).', verbose_name='Vorstandsmitglied'),
        ),
    ]
