# Generated by Django 6.1.1 on 2026-09-27 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_matrix_und_tags'),
        ('members', '0003_vorstand_und_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitgliedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='z. B. Vorstand, Kassenwart, Schriftführer', max_length=100, verbose_name='Name')),
                ('beschreibung', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('paperless_gruppe', models.CharField(blank=True, help_text='Leer = kein Paperless-Zugang über dieses Tag. Sonst wird für Träger des Tags ein Paperless-Konto angelegt und dieser Gruppe zugeordnet (Gruppe wird bei Bedarf angelegt).', max_length=150, verbose_name='Paperless-Gruppe')),
                ('paperless_nur_lesen', models.BooleanField(default=False, help_text='Gilt für neu angelegte Gruppen: nur Dokumente ansehen statt ansehen, hochladen und bearbeiten.', verbose_name='In Paperless nur lesen')),
                ('openslides_gruppe', models.CharField(blank=True, help_text='Name der Gruppe in der OpenSlides-Versammlung (z. B. Admin, Staff, Delegates). Träger des Tags erhalten beim Anlegen bzw. Übertragen einer Veranstaltung diese Rechte. Leer = keine.', max_length=100, verbose_name='OpenSlides-Gruppe in Versammlungen')),
                ('rolle', models.ForeignKey(blank=True, help_text='Träger des Tags erhalten (sofern sie einen Benutzerzugang haben) automatisch diese Rolle; fällt das Tag weg, wird der Zugang deaktiviert (Rechte entziehen nach Funktionsende).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.rolle', verbose_name='Rolle in dieser Software')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Tag (Zugriffsrechte)',
                'verbose_name_plural': 'Tags (Zugriffsrechte)',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mitglied',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Bestimmen die Zugriffsrechte in Paperless und OpenSlides (Verwaltung › Tags).', related_name='mitglieder', to='members.mitgliedtag', verbose_name='Tags (Zugriffsrechte)'),
        ),
    ]
