# Generated by Django 6.1.1 on 2026-10-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_matrix_und_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='vorstandsmitglied',
            field=models.BooleanField(default=False, editable=False, help_text='Wird automatisch anhand der Tags geführt (DSO-Funktionen bzw. Beisitzer) - keine manuelle Auswahl mehr, sondern über Verwaltung › Funktionen: Tags vergeben. Setzt automatisch die Funktion „Vorstandsmitglied“. Nur Vorstandsmitglieder können mit Paperless abgeglichen werden (Verwaltung › Paperless-Anbindung).', verbose_name='Vorstandsmitglied'),
        ),
    ]
