# Generated by Django 6.1.1 on 2026-09-20 20:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zuwendungsbestaetigung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('nummer', models.CharField(blank=True, editable=False, max_length=30, verbose_name='Nummer')),
                ('typ', models.CharField(choices=[('einzel', 'Einzelbestätigung'), ('sammel', 'Sammelbestätigung')], default='einzel', max_length=8, verbose_name='Typ')),
                ('art', models.CharField(choices=[('geld', 'Geldzuwendung'), ('sach', 'Sachzuwendung')], default='geld', max_length=6, verbose_name='Art')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('ausgestellt', 'Ausgestellt'), ('storniert', 'Storniert')], default='entwurf', editable=False, max_length=12, verbose_name='Status')),
                ('spender_name', models.CharField(max_length=200, verbose_name='Zuwendender')),
                ('spender_anschrift', models.CharField(max_length=300, verbose_name='Anschrift des Zuwendenden')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (€)')),
                ('datum_von', models.DateField(verbose_name='Zuwendung von')),
                ('datum_bis', models.DateField(verbose_name='Zuwendung bis')),
                ('ist_mitgliedsbeitrag', models.BooleanField(default=False, verbose_name='Es handelt sich um einen Mitgliedsbeitrag')),
                ('verzicht_aufwendungen', models.BooleanField(default=False, verbose_name='Verzicht auf Erstattung von Aufwendungen')),
                ('sach_beschreibung', models.TextField(blank=True, verbose_name='Bezeichnung der Sachzuwendung')),
                ('sach_herkunft', models.CharField(blank=True, max_length=200, verbose_name='Herkunft der Sachzuwendung')),
                ('sach_wertermittlung', models.CharField(blank=True, max_length=200, verbose_name='Wertermittlung')),
                ('ausgestellt_am', models.DateField(blank=True, editable=False, null=True, verbose_name='Ausgestellt am')),
                ('vereinsdaten', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Vereinsdaten zum Ausstellungszeitpunkt')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Spendenquittung',
                'verbose_name_plural': 'Spendenquittungen (Zuwendungsbestätigungen)',
                'ordering': ['-datum_bis', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Spende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('spender_name', models.CharField(blank=True, max_length=200, verbose_name='Spender (Name, falls kein Mitglied)')),
                ('spender_anschrift', models.CharField(blank=True, max_length=300, verbose_name='Anschrift (falls kein Mitglied)')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Datum der Zuwendung')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag / Wert (€)')),
                ('art', models.CharField(choices=[('geld', 'Geldspende'), ('sach', 'Sachspende'), ('mitgliedsbeitrag', 'Mitgliedsbeitrag'), ('aufwandsverzicht', 'Aufwandsspende (Verzicht auf Erstattung)')], default='geld', max_length=20, verbose_name='Art')),
                ('zweck', models.CharField(blank=True, max_length=200, verbose_name='Verwendungszweck')),
                ('sach_beschreibung', models.TextField(blank=True, verbose_name='Bezeichnung der Sachspende')),
                ('sach_herkunft', models.CharField(blank=True, choices=[('', 'keine Angabe'), ('privat', 'Privatvermögen'), ('betrieb', 'Betriebsvermögen')], max_length=10, verbose_name='Herkunft')),
                ('sach_wertermittlung', models.CharField(blank=True, help_text='z. B. Kaufbeleg, Schätzung, Gutachten', max_length=200, verbose_name='Wertermittlung')),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('bankumsatz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.bankumsatz', verbose_name='Bankumsatz')),
                ('spender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.mitglied', verbose_name='Spender (Mitglied)')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('bestaetigung', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spenden', to='donations.zuwendungsbestaetigung', verbose_name='Spendenquittung')),
            ],
            options={
                'verbose_name': 'Spende',
                'verbose_name_plural': 'Spenden',
                'ordering': ['-datum', '-id'],
            },
        ),
    ]
