# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankumsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('buchungsdatum', models.DateField(verbose_name='Buchungsdatum')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (€)')),
                ('gegenkonto_name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('gegenkonto_iban', apps.core.fields.VerschluesseltesTextField(blank=True, verbose_name='IBAN')),
                ('verwendungszweck', models.TextField(blank=True, verbose_name='Verwendungszweck')),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('zugeordnet', 'Zugeordnet'), ('manuell', 'Manuelle Zuordnung erforderlich'), ('ignoriert', 'Ignoriert')], default='neu', max_length=12, verbose_name='Status')),
                ('pruefsumme', models.CharField(blank=True, editable=False, max_length=40)),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Bankumsatz',
                'verbose_name_plural': 'Bankumsätze',
                'ordering': ['-buchungsdatum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Beitragsjahr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('jahr', models.PositiveIntegerField(verbose_name='Jahr')),
                ('faelligkeit', models.DateField(verbose_name='Fälligkeit')),
                ('alters_stichtag', models.DateField(verbose_name='Stichtag für Altersregeln')),
                ('abgerechnet_am', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Abgerechnet am')),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Beitragsjahr',
                'verbose_name_plural': 'Beitragsjahre',
                'ordering': ['-jahr'],
            },
        ),
        migrations.CreateModel(
            name='Beitragsregel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('nur_familie', models.BooleanField(default=False, help_text="Betrag wird nur beim 'Familienzahler' berechnet", verbose_name='Nur Familienmitgliedschaften')),
                ('alter_von', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alter von')),
                ('alter_bis', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alter bis (einschl.)')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Jahresbeitrag (€)')),
                ('prioritaet', models.IntegerField(default=10, verbose_name='Priorität (höher = zuerst)')),
                ('gueltig_ab_jahr', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gültig ab Jahr')),
                ('gueltig_bis_jahr', models.PositiveIntegerField(blank=True, null=True, verbose_name='Gültig bis Jahr')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('mitgliedsart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.mitgliedsart', verbose_name='Nur für Mitgliedsart')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Beitragsregel',
                'verbose_name_plural': 'Beitragsregeln',
                'ordering': ['-prioritaet', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('nummer', models.CharField(blank=True, default=None, editable=False, max_length=30, null=True, verbose_name='Rechnungsnummer')),
                ('typ', models.CharField(choices=[('beitrag', 'Beitragsrechnung'), ('individuell', 'Individuelle Rechnung'), ('sammel', 'Sammelrechnung'), ('gutschrift', 'Gutschrift'), ('storno', 'Storno')], default='individuell', max_length=12, verbose_name='Art')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('offen', 'Offen'), ('teilbezahlt', 'Teilweise bezahlt'), ('bezahlt', 'Bezahlt'), ('storniert', 'Storniert'), ('verbucht', 'Verbucht')], default='entwurf', max_length=12, verbose_name='Status')),
                ('empfaenger_name', models.CharField(blank=True, max_length=200, verbose_name='Empfänger')),
                ('empfaenger_anschrift', models.TextField(blank=True, verbose_name='Anschrift des Empfängers')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Rechnungsdatum')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='Fällig am')),
                ('jahr', models.PositiveIntegerField(blank=True, null=True, verbose_name='Beitragsjahr')),
                ('zeitraum_von', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum von')),
                ('zeitraum_bis', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum bis')),
                ('betrag', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Betrag (€)')),
                ('kopftext', models.TextField(blank=True, verbose_name='Text oben')),
                ('fusstext', models.TextField(blank=True, verbose_name='Text unten')),
                ('versendet_am', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Per E-Mail versendet')),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('mitglied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.mitglied', verbose_name='Mitglied')),
                ('storno_von', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gegenbuchungen', to='finance.rechnung', verbose_name='Bezieht sich auf')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Mahnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('stufe', models.PositiveSmallIntegerField(choices=[(1, 'Zahlungserinnerung'), (2, '1. Mahnung'), (3, '2. Mahnung / letzte Mahnung')], default=1, verbose_name='Stufe')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('frist', models.DateField(verbose_name='Neue Zahlungsfrist')),
                ('gebuehr', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Mahngebühr (€)')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mahnungen', to='finance.rechnung', verbose_name='Rechnung')),
            ],
            options={
                'verbose_name': 'Mahnung',
                'verbose_name_plural': 'Mahnungen',
                'ordering': ['-datum', '-stufe'],
            },
        ),
        migrations.CreateModel(
            name='Rechnungsposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300, verbose_name='Bezeichnung')),
                ('menge', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Menge')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (€)')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='finance.rechnung', verbose_name='Rechnung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Rechnungsposition',
                'verbose_name_plural': 'Rechnungspositionen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Zahlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Zahlungsdatum')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (€)')),
                ('art', models.CharField(choices=[('ueberweisung', 'Überweisung'), ('lastschrift', 'SEPA-Lastschrift'), ('bar', 'Bar'), ('sonstige', 'Sonstige')], default='ueberweisung', max_length=12, verbose_name='Zahlungsart')),
                ('ruecklastschrift', models.BooleanField(default=False, verbose_name='Rücklastschrift (Betrag wird abgezogen)')),
                ('referenz', models.CharField(blank=True, max_length=200, verbose_name='Referenz')),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('bankumsatz', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zahlung', to='finance.bankumsatz')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zahlungen', to='finance.rechnung', verbose_name='Rechnung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankumsatz',
            index=models.Index(fields=['verein', 'pruefsumme'], name='finance_ban_verein__f90ca6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='beitragsjahr',
            unique_together={('verein', 'jahr')},
        ),
        migrations.AlterUniqueTogether(
            name='rechnung',
            unique_together={('verein', 'nummer')},
        ),
    ]
