# Generated by Django 6.1.1 on 2026-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahlung',
            name='art',
            field=models.CharField(choices=[('ueberweisung', 'Überweisung'), ('lastschrift', 'SEPA-Lastschrift'), ('bar', 'Bar'), ('rueckzahlung', 'Rückzahlung'), ('sonstige', 'Sonstige')], default='ueberweisung', max_length=12, verbose_name='Zahlungsart'),
        ),
    ]
