# Generated by Django 6.1.1 on 2026-09-22 20:48

import apps.core.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_verein_akzentfarbe_fuss'),
        ('finance', '0002_alter_zahlung_art'),
        ('members', '0002_mitglied_benutzer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaEinzug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('nummer', models.CharField(editable=False, max_length=30, verbose_name='Nummer')),
                ('faelligkeitsdatum', models.DateField(verbose_name='Fälligkeitsdatum (Einzugstermin)')),
                ('anzahl', models.PositiveIntegerField(default=0, editable=False, verbose_name='Anzahl Lastschriften')),
                ('summe', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Summe (€)')),
                ('datei', models.FileField(editable=False, upload_to=apps.core.util.upload_pfad, verbose_name='SEPA-XML-Datei')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'SEPA-Einzug',
                'verbose_name_plural': 'SEPA-Einzüge',
                'ordering': ['-erstellt'],
                'unique_together': {('verein', 'nummer')},
            },
        ),
        migrations.CreateModel(
            name='SepaEinzugPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (€)')),
                ('mandatsreferenz', models.CharField(max_length=35, verbose_name='SEPA-Mandatsreferenz')),
                ('mandatsdatum', models.DateField(verbose_name='Datum des SEPA-Mandats')),
                ('sequenztyp', models.CharField(choices=[('FRST', 'Erstlastschrift (FRST)'), ('RCUR', 'Folgelastschrift (RCUR)')], max_length=4, verbose_name='Sequenztyp')),
                ('einzug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='finance.sepaeinzug', verbose_name='Einzug')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.mitglied', verbose_name='Mitglied')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sepa_positionen', to='finance.rechnung', verbose_name='Rechnung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'SEPA-Einzugsposition',
                'verbose_name_plural': 'SEPA-Einzugspositionen',
                'ordering': ['id'],
            },
        ),
    ]
