# Generated by Django 6.1.1 on 2026-09-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_sepaeinzug_sepaeinzugposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='nettobetrag',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Nettobetrag (€)'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='steuerbetrag',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Umsatzsteuer (€)'),
        ),
        migrations.AddField(
            model_name='rechnungsposition',
            name='steuersatz',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 für umsatzsteuerfreie Positionen (z. B. ideeller Bereich).', max_digits=5, verbose_name='Umsatzsteuersatz (%)'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='betrag',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Betrag brutto (€)'),
        ),
        migrations.AlterField(
            model_name='rechnungsposition',
            name='einzelpreis',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis netto (€)'),
        ),
    ]
