# Generated by Django 6.1.1 on 2026-09-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_verein_rechnung_steuerhinweis_and_more'),
        ('finance', '0004_rechnung_nettobetrag_rechnung_steuerbetrag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinTSZugang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('blz', models.CharField(max_length=8, verbose_name='Bankleitzahl')),
                ('kennung', models.CharField(help_text='Die Kennung fürs Online-Banking, nicht die PIN', max_length=100, verbose_name='Online-Banking-Kennung')),
                ('bank_url', models.URLField(help_text='Von der Bank vorgegebene FinTS-Serveradresse, z. B. https://banking.beispielbank.de/fints30', verbose_name='FinTS-Adresse der Bank')),
                ('tage', models.PositiveIntegerField(default=60, verbose_name='Tage rückwirkend abrufen')),
                ('letzter_abruf', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Letzter erfolgreicher Abruf')),
                ('letzte_meldung', models.CharField(blank=True, editable=False, max_length=300, verbose_name='Letzte Meldung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'FinTS-Zugang',
                'verbose_name_plural': 'FinTS-Zugänge',
                'constraints': [models.UniqueConstraint(fields=('verein',), name='ein_fints_zugang_je_verein')],
            },
        ),
    ]
