# Generated by Django 6.1.1 on 2026-09-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_fintszugang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fintszugang',
            options={'ordering': ['bezeichnung'], 'verbose_name': 'FinTS-Zugang', 'verbose_name_plural': 'FinTS-Zugänge'},
        ),
        migrations.RemoveConstraint(
            model_name='fintszugang',
            name='ein_fints_zugang_je_verein',
        ),
        migrations.AddField(
            model_name='bankumsatz',
            name='fints_zugang',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankumsaetze', to='finance.fintszugang', verbose_name='FinTS-Zugang'),
        ),
        migrations.AddField(
            model_name='fintszugang',
            name='bezeichnung',
            field=models.CharField(default='', help_text='Zur Unterscheidung, wenn mehrere Zugänge angelegt sind, z. B. Name der Bank', max_length=100, verbose_name='Bezeichnung'),
        ),
    ]
