# Generated by Django 6.1.1 on 2026-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_fintszugang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fintszugang',
            name='abzurufende_ibans',
            field=models.TextField(blank=True, help_text='Kommagetrennt. Leer = alle Konten dieses Zugangs werden abgerufen (Standard). Ein Online-Banking-Zugang deckt oft mehrere Konten ab - hier lässt sich der Abruf auf einzelne davon beschränken. Über „Kontodaten abrufen“ bequem per Haken auswählbar.', verbose_name='Abzurufende Konten (IBAN)'),
        ),
    ]
