# Generated by Django 6.1.1 on 2026-10-07 22:02, danach um die Verschluesselung bestehender Werte ergaenzt.
"""Die Online-Banking-Kennung (Login-Name fuers Online-Banking, keine PIN) wurde bisher unverschluesselt als
CharField gespeichert - wie IBAN/API-Token wird sie jetzt per VerschluesseltesTextField verschluesselt.

Ablauf bewusst dreigeteilt: zuerst auf ein einfaches TextField verbreitern (ein Fernet-Token ist laenger als die
bisherigen 100 Zeichen), DANN die schon vorhandenen Klartext-Werte verschluesseln (noch im TextField-Zustand
gelesen/geschrieben, also ohne automatische Ver-/Entschluesselung durch das Feld selbst), erst ZULETZT auf das
echte VerschluesseltesTextField umstellen - sonst wuerde das Lesen der noch unverschluesselten Altdaten im
verschluesselten Feldzustand sofort mit ImproperlyConfigured/InvalidToken fehlschlagen.

Nutzt bewusst apps.core.fields._fernet() (reine Krypto-Infrastruktur, kein fachlicher Code) statt die
Verschluesselung hier zu duplizieren. Liest/schreibt bewusst per Roh-SQL statt ueber apps.get_model(): bei
RunPython.reverse_code reicht Django als "from_state" den Zustand NACH der (in Vorwaertsrichtung) folgenden
AlterField-Operation durch, das Feld waere beim Rueckwaertslauf also bereits wieder als VerschluesseltesTextField
im Modell-State - ueber die ORM gelesen wuerde dann doppelt entschluesselt. Roh-SQL umgeht diese Modell-State-
Abhaengigkeit komplett und funktioniert in beide Richtungen unabhaengig vom gerade aktiven Feldtyp im State."""
from django.db import connection, migrations, models

import apps.core.fields


def _zeilen():
    with connection.cursor() as c:
        c.execute("SELECT id, kennung FROM finance_fintszugang WHERE kennung != ''")
        return c.fetchall()


def verschluesseln(apps, schema_editor):
    from apps.core.fields import _fernet
    f = _fernet()
    with connection.cursor() as c:
        for pk, wert in _zeilen():
            c.execute("UPDATE finance_fintszugang SET kennung = %s WHERE id = %s",
                      [f.encrypt(wert.encode()).decode(), pk])


def entschluesseln(apps, schema_editor):
    from cryptography.fernet import InvalidToken

    from apps.core.fields import _fernet
    f = _fernet()
    with connection.cursor() as c:
        for pk, wert in _zeilen():
            try:
                klartext = f.decrypt(wert.encode()).decode()
            except InvalidToken:
                continue   # war schon unverschluesselt (z. B. erneutes Zurueckrollen) - unveraendert lassen
            c.execute("UPDATE finance_fintszugang SET kennung = %s WHERE id = %s", [klartext, pk])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fints_konten_auswahl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fintszugang',
            name='kennung',
            field=models.TextField(help_text='Die Kennung fürs Online-Banking, nicht die PIN',
                                   verbose_name='Online-Banking-Kennung'),
        ),
        migrations.RunPython(verschluesseln, entschluesseln),
        migrations.AlterField(
            model_name='fintszugang',
            name='kennung',
            field=apps.core.fields.VerschluesseltesTextField(help_text='Die Kennung fürs Online-Banking, nicht die PIN', verbose_name='Online-Banking-Kennung'),
        ),
    ]
