# Generated by Django 6.1.2 on 2026-10-08 22:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_fintszugang_kennung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungsposition',
            name='einzelpreis',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Einzelpreis netto (€)'),
        ),
        migrations.AlterField(
            model_name='rechnungsposition',
            name='menge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='zahlung',
            name='betrag',
            field=models.DecimalField(decimal_places=2, help_text='immer positiv erfassen', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Betrag (€)'),
        ),
    ]
