# Generated by Django 6.1.2 on 2026-10-09 05:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_rechnungsposition_einzelpreis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahnung',
            name='gebuehr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mahngebühr (€)'),
        ),
    ]
