# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.util
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('kuerzel', models.SlugField(unique=True, verbose_name='Kürzel')),
                ('anschrift', models.CharField(blank=True, max_length=200, verbose_name='Straße / Nr.')),
                ('plz', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('vereinsregister', models.CharField(blank=True, max_length=100, verbose_name='Registergericht / Nr.')),
                ('bankname', models.CharField(blank=True, max_length=100, verbose_name='Bank')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('glaeubiger_id', models.CharField(blank=True, max_length=35, verbose_name='Gläubiger-ID (SEPA)')),
                ('finanzamt', models.CharField(blank=True, max_length=100, verbose_name='Finanzamt')),
                ('steuernummer', models.CharField(blank=True, max_length=30, verbose_name='Steuernummer')),
                ('bescheid_art', models.CharField(choices=[('freistellung', 'Freistellungsbescheid'), ('anlage', 'Anlage zum Körperschaftsteuerbescheid'), ('feststellung', 'Feststellungsbescheid nach § 60a AO')], default='freistellung', max_length=20, verbose_name='Art des Gemeinnützigkeitsbescheids')),
                ('bescheid_datum', models.DateField(blank=True, null=True, verbose_name='Datum des Bescheids')),
                ('bescheid_zeitraum', models.CharField(blank=True, max_length=100, verbose_name='Bescheid gilt für Zeitraum / VZ')),
                ('beguenstigte_zwecke', models.TextField(blank=True, verbose_name='Begünstigte Zwecke (laut Satzung)')),
                ('zahlungsziel_tage', models.PositiveIntegerField(default=14, verbose_name='Zahlungsziel (Tage)')),
                ('rechnung_kopftext', models.TextField(blank=True, verbose_name='Rechnungstext oben')),
                ('rechnung_fusstext', models.TextField(blank=True, default='Bitte überweisen Sie den Betrag unter Angabe des Verwendungszwecks.', verbose_name='Rechnungstext unten')),
                ('uebungsleiter_freibetrag', models.DecimalField(decimal_places=2, default=3300, max_digits=8, verbose_name='Übungsleiterfreibetrag / Jahr (€)')),
                ('ehrenamts_freibetrag', models.DecimalField(decimal_places=2, default=960, max_digits=8, verbose_name='Ehrenamtsfreibetrag / Jahr (€)')),
                ('logo', models.ImageField(blank=True, help_text='Wird auf Briefen, Rechnungen und Word-Dokumenten oben rechts gedruckt.', upload_to=apps.core.util.logo_pfad, verbose_name='Vereinslogo (PNG oder JPG)')),
                ('unterschrift_1', models.CharField(blank=True, help_text='z. B. Max Mustermann, 1. Vorsitzender', max_length=150, verbose_name='Unterschrift 1 (Briefe)')),
                ('unterschrift_2', models.CharField(blank=True, max_length=150, verbose_name='Unterschrift 2 (Briefe)')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Verein',
                'verbose_name_plural': 'Vereine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('ist_superadmin', models.BooleanField(default=False, verbose_name='Superadministrator (alle Rechte)')),
                ('rechte', models.JSONField(blank=True, default=list, verbose_name='Rechte')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollen', to='core.verein')),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Rollen',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Nummernkreis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schluessel', models.CharField(max_length=20)),
                ('jahr', models.PositiveIntegerField(default=0)),
                ('letzter', models.PositiveIntegerField(default=0)),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.verein')),
            ],
            options={
                'unique_together': {('verein', 'schluessel', 'jahr')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('user_name', models.CharField(blank=True, max_length=150, verbose_name='Benutzer')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('modell', models.CharField(max_length=100, verbose_name='Objektart')),
                ('objekt_id', models.CharField(max_length=40, verbose_name='Objekt-ID')),
                ('objekt_repr', models.CharField(max_length=200, verbose_name='Objekt')),
                ('aktion', models.CharField(choices=[('angelegt', 'Angelegt'), ('geaendert', 'Geändert'), ('geloescht', 'Gelöscht'), ('exportiert', 'Exportiert'), ('importiert', 'Importiert')], max_length=12, verbose_name='Aktion')),
                ('aenderungen', models.JSONField(default=dict, verbose_name='Änderungen')),
                ('grund', models.CharField(blank=True, max_length=200, verbose_name='Grund')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Protokolleintrag',
                'verbose_name_plural': 'Änderungsprotokoll',
                'ordering': ['-zeit', '-id'],
                'indexes': [models.Index(fields=['verein', 'modell', 'objekt_id'], name='core_auditl_verein__c9314b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Zugang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_rechte', models.JSONField(blank=True, default=list, verbose_name='Zusätzliche Einzelrechte')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rolle', verbose_name='Rolle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zugaenge', to=settings.AUTH_USER_MODEL)),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zugaenge', to='core.verein')),
            ],
            options={
                'verbose_name': 'Benutzerzugang',
                'verbose_name_plural': 'Benutzerzugänge',
                'unique_together': {('verein', 'user')},
            },
        ),
    ]
