# Generated by Django 6.1.1 on 2026-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='akzentfarbe',
            field=models.CharField(default='#1F4E79', help_text='Hex-Code, z. B. #1F4E79 – für Überschrift und Linie im Briefkopf.', max_length=7, verbose_name='Akzentfarbe für Briefe/PDFs'),
        ),
    ]
