# Generated by Django 6.1.1 on 2026-09-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verein_akzentfarbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='akzentfarbe_fuss',
            field=models.CharField(blank=True, help_text='Optional, Hex-Code z. B. #005199. Leer = gleiche Farbe wie oben.', max_length=7, verbose_name='Zweite Akzentfarbe (Linie über der Fußzeile)'),
        ),
    ]
