# Generated by Django 6.1.1 on 2026-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_verein_akzentfarbe_fuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='impressum_text',
            field=models.TextField(blank=True, help_text='Vollständiger Text nach § 5 TMG / § 18 MStV (verantwortliche Person, Anschrift, Kontakt, Vertretungsberechtigte, ggf. USt-IdNr.). Wird ungeprüft auf der öffentlich erreichbaren Impressum-Seite angezeigt – bitte gegen die eigene Satzung/das Vereinsregister prüfen.', verbose_name='Impressum'),
        ),
    ]
