# Generated by Django 6.1.1 on 2026-09-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_verein_impressum_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='akzentfarbe',
            field=models.CharField(default='#1F4E79', help_text='Hex-Code, z. B. #1F4E79 – für Überschrift/Linie im Briefkopf sowie Navigationsleiste und Schaltflächen in der Weboberfläche.', max_length=7, verbose_name='Akzentfarbe (Briefe, PDFs und Weboberfläche)'),
        ),
    ]
