# Generated by Django 6.1.1 on 2026-09-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_verein_akzentfarbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='rechnung_steuerhinweis',
            field=models.CharField(blank=True, help_text='Freitext für Rechnungen/E-Rechnungen, wenn (ein Teil) der Rechnung mit 0 % Umsatzsteuer ausgewiesen wird, z. B. „Gemäß § 19 UStG wird keine Umsatzsteuer berechnet“ oder eine passende Befreiungsvorschrift. Leer lassen für den Standardtext „Steuerbefreiung nach § 4 UStG (ideeller Bereich)“. Bitte durch Steuerberater prüfen lassen.', max_length=300, verbose_name='Steuerhinweis auf Rechnungen ohne Umsatzsteuer'),
        ),
        migrations.AddField(
            model_name='verein',
            name='umsatzsteuerpflichtig',
            field=models.BooleanField(default=False, help_text='Für nicht gemeinnützige Vereine bzw. den wirtschaftlichen Geschäftsbetrieb: neue Rechnungspositionen schlagen dann standardmäßig Umsatzsteuer vor, Rechnungen/E-Rechnungen weisen sie entsprechend aus. Ersetzt keine steuerliche Beratung.', verbose_name='Umsatzsteuerpflichtig'),
        ),
        migrations.AddField(
            model_name='verein',
            name='ust_idnr',
            field=models.CharField(blank=True, max_length=20, verbose_name='USt-IdNr.'),
        ),
    ]
