# Generated by Django 6.1.1 on 2026-09-24 20:54

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_verein_rechnung_steuerhinweis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systemeinstellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fints_produkt_id', apps.core.fields.VerschluesseltesTextField(blank=True, help_text='Alternative zur Umgebungsvariable FINTS_PRODUCT_ID - wird bevorzugt verwendet, wenn gesetzt. Kostenlos zu registrieren bei der Deutschen Kreditwirtschaft: https://www.hbci-zka.de/register/prod_register.htm', verbose_name='FinTS-Produkt-ID')),
            ],
            options={
                'verbose_name': 'Systemeinstellung',
                'verbose_name_plural': 'Systemeinstellungen',
            },
        ),
    ]
