# Generated by Django 6.1.1 on 2026-09-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemeinstellung'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemeinstellung',
            name='update_geprueft_am',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zuletzt auf Updates geprüft'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='update_verfuegbare_version',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Verfügbare neue Version'),
        ),
    ]
