# Generated by Django 6.1.1 on 2026-09-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemeinstellung_update_geprueft_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolle',
            name='matrix',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Berechtigungsmatrix (Stufen je Datenbereich)'),
        ),
    ]
