# Generated by Django 6.1.1 on 2026-10-08 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_altes_rollensystem_abloesen'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='etikett_breite_mm',
            field=models.PositiveIntegerField(default=58, help_text='Für Inventar-Etiketten (QR-Code). Standard passt auf gängige A4-Etikettenbögen. Für einen Etikettendrucker mit Endlosrolle (z. B. Dymo LabelWriter 450, Standardadresse 89 × 28 mm) hier die Rollenbreite eintragen und „Etiketten je Zeile“/„Etikettenzeilen je Seite“ unten jeweils auf 1 setzen – die PDF-Seite wird dann exakt auf diese Größe zugeschnitten statt auf A4.', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Etikettenbreite (mm)'),
        ),
        migrations.AddField(
            model_name='verein',
            name='etikett_hoehe_mm',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Etikettenhöhe (mm)'),
        ),
        migrations.AddField(
            model_name='verein',
            name='etikett_spalten',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Etiketten je Zeile (Spalten)'),
        ),
        migrations.AddField(
            model_name='verein',
            name='etikett_zeilen',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Etikettenzeilen je Seite'),
        ),
    ]
