# Generated by Django 6.1.1 on 2026-10-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_verein_etikett_breite_mm_verein_etikett_hoehe_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='akzentfarbe',
            field=models.CharField(default='#AF2B1E', help_text='Hex-Code, z. B. #AF2B1E (Feuerwehrrot) – für Überschrift/Linie im Briefkopf sowie Navigationsleiste und Schaltflächen in der Weboberfläche. Unter dem Farbfeld stehen gängige Feuerwehr-Farben zur Auswahl, es kann aber jede beliebige Farbe eingetragen werden.', max_length=7, verbose_name='Akzentfarbe (Briefe, PDFs und Weboberfläche)'),
        ),
    ]
