# Generated by Django 6.1.1 on 2026-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_verein_akzentfarbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='akzentfarbe_web',
            field=models.CharField(blank=True, help_text='Optional eigene Farbe nur für Navigationsleiste und Schaltflächen in der Anwendung, unabhängig von Briefen/PDFs. Leer = gleiche Farbe wie oben.', max_length=7, verbose_name='Akzentfarbe (Weboberfläche)'),
        ),
        migrations.AlterField(
            model_name='verein',
            name='akzentfarbe',
            field=models.CharField(default='#AF2B1E', help_text='Hex-Code, z. B. #AF2B1E (Feuerwehrrot) – für Überschrift/Linie im Briefkopf. Gilt auch für die Weboberfläche, solange unten keine eigene Farbe dafür eingetragen ist. Unter dem Farbfeld stehen gängige Feuerwehr-Farben zur Auswahl, es kann aber jede beliebige Farbe eingetragen werden.', max_length=7, verbose_name='Akzentfarbe (Briefe und PDFs)'),
        ),
        migrations.AlterField(
            model_name='verein',
            name='akzentfarbe_fuss',
            field=models.CharField(blank=True, help_text='Optional, Hex-Code z. B. #005199. Leer = gleiche Farbe wie oben (für Briefe/PDFs).', max_length=7, verbose_name='Zweite Akzentfarbe (Linie über der Fußzeile)'),
        ),
    ]
