# Generated by Django 6.1.1 on 2026-10-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_verein_akzentfarbe_web_alter_verein_akzentfarbe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='akzentfarbe_web_2',
            field=models.CharField(blank=True, help_text='Optional, für Farbverläufe in Navigation und Schaltflächen (z. B. Rot nach Schwarz). Leer = automatisch aus der ersten Web-Akzentfarbe abgeleitet.', max_length=7, verbose_name='Zweite Akzentfarbe (Weboberfläche, für Farbverläufe)'),
        ),
    ]
