# Generated by Django 6.1.1 on 2026-10-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_verein_akzentfarbe_web_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='akzentfarbe_web_3',
            field=models.CharField(blank=True, help_text='Optional, für Icon-Hintergründe auf den Kennzahlen-Karten und ähnliche Hervorhebungen. Leer = Leuchtgelb (#F7FA00). Die Textfarbe darauf wird automatisch für Lesbarkeit berechnet.', max_length=7, verbose_name='Akzentfarbe 2 (Weboberfläche, für Hervorhebungen)'),
        ),
        migrations.AlterField(
            model_name='verein',
            name='akzentfarbe_web',
            field=models.CharField(blank=True, help_text='Optional eigene Farbe nur für Navigationsleiste und Schaltflächen in der Anwendung, unabhängig von Briefen/PDFs. Leer = gleiche Farbe wie oben.', max_length=7, verbose_name='Hauptfarbe (Weboberfläche)'),
        ),
        migrations.AlterField(
            model_name='verein',
            name='akzentfarbe_web_2',
            field=models.CharField(blank=True, help_text='Optional, für Farbverläufe in Navigation und Schaltflächen (z. B. Rot nach Schwarz). Leer = automatisch aus der Hauptfarbe abgeleitet (dunklere Stufe).', max_length=7, verbose_name='Akzentfarbe 1 (Weboberfläche, für Farbverläufe)'),
        ),
    ]
