# Generated by Django 6.1.2 on 2026-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_verein_akzentfarbe_web_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='startseite_banner',
            field=models.TextField(blank=True, help_text='Wird oben auf der Startseite allen angemeldeten Benutzern dieses Vereins angezeigt, bis entfernt oder das Bis-Datum erreicht ist - z. B. für Hinweise zur nächsten Mitgliederversammlung oder geplante Wartungsarbeiten. Leer = kein Banner.', verbose_name='Benachrichtigungsbanner (Startseite)'),
        ),
        migrations.AddField(
            model_name='verein',
            name='startseite_banner_art',
            field=models.CharField(choices=[('info', 'Info'), ('warnung', 'Warnung'), ('wichtig', 'Wichtig')], default='info', max_length=8, verbose_name='Art des Banners'),
        ),
        migrations.AddField(
            model_name='verein',
            name='startseite_banner_bis',
            field=models.DateField(blank=True, help_text='Leer = dauerhaft sichtbar, bis der Text hier entfernt wird.', null=True, verbose_name='Banner sichtbar bis'),
        ),
    ]
