# Generated by Django 6.1.2 on 2026-10-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_verein_startseite_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verein',
            name='aufgaben_geprueft_am',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zuletzt auf überfällige Aufgaben geprüft'),
        ),
    ]
