# Generated by Django 6.1.2 on 2026-10-09 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_verein_aufgaben_geprueft_am'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardEinstellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kacheln_reihenfolge', models.JSONField(blank=True, default=list, verbose_name='Kachel-Reihenfolge')),
                ('kacheln_ausgeblendet', models.JSONField(blank=True, default=list, verbose_name='Ausgeblendete Kacheln')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_einstellung', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard-Einstellung',
                'verbose_name_plural': 'Dashboard-Einstellungen',
            },
        ),
    ]
