# Generated by Django 6.1.2 on 2026-10-10 12:30

import apps.core.fields
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dashboardeinstellung'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_aktiv',
            field=models.BooleanField(default=False, verbose_name='Automatische Sicherung aktiv'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_aufbewahren',
            field=models.PositiveSmallIntegerField(default=14, help_text='Anzahl der zuletzt behaltenen Sicherungen - lokal und am externen Ziel; ältere werden gelöscht.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sicherungen aufbewahren'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_letzte_meldung',
            field=models.TextField(blank=True, editable=False, verbose_name='Ergebnis der letzten Sicherung'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_letzter_lauf',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Letzte Sicherung'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_letzter_ok',
            field=models.BooleanField(default=True, editable=False, verbose_name='Letzte Sicherung erfolgreich'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_letzter_test',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='Letzter Verbindungstest'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_uhrzeit',
            field=models.TimeField(default=datetime.time(3, 0), verbose_name='Uhrzeit der täglichen Sicherung'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='sicherung_ziel',
            field=models.CharField(blank=True, choices=[('', 'Nur lokal (Docker-Volume)'), ('sftp', 'SFTP / SSH (z. B. NAS)'), ('smb', 'SMB-Freigabe (Windows-/NAS-Freigabe)')], help_text='Zusätzlich zur lokalen Kopie wird jede Sicherung hierhin kopiert.', max_length=4, verbose_name='Externes Ziel'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='ziel_benutzer',
            field=models.CharField(blank=True, help_text='Bei SMB ggf. mit Domäne: DOMÄNE\\Benutzer', max_length=150, verbose_name='Benutzername'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='ziel_host',
            field=models.CharField(blank=True, help_text='Hostname oder IP-Adresse, z. B. nas.local oder 192.168.1.20', max_length=253, verbose_name='Server / NAS'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='ziel_hostkey',
            field=models.CharField(blank=True, help_text='Wird beim ersten erfolgreichen „Verbindung testen“ übernommen und danach bei jeder Verbindung geprüft. Leeren, wenn der Server absichtlich neu aufgesetzt wurde.', max_length=120, verbose_name='Hostschlüssel-Fingerabdruck (SFTP)'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='ziel_passwort',
            field=apps.core.fields.VerschluesseltesTextField(blank=True, verbose_name='Passwort'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='ziel_port',
            field=models.PositiveIntegerField(blank=True, help_text='Leer = Standard (SFTP 22, SMB 445)', null=True, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='ziel_schluessel',
            field=apps.core.fields.VerschluesseltesTextField(blank=True, help_text='Alternative zum Passwort: kompletter Inhalt der Schlüsseldatei (OpenSSH/PEM).', verbose_name='Privater SSH-Schlüssel (optional, nur SFTP)'),
        ),
        migrations.AddField(
            model_name='systemeinstellung',
            name='ziel_verzeichnis',
            field=models.CharField(blank=True, help_text='SFTP: Pfad auf dem Server, z. B. /volume1/backup/feuerix. SMB: Freigabe und Unterordner, z. B. backup/feuerix', max_length=300, verbose_name='Zielverzeichnis'),
        ),
    ]
