# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.util
import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchungskategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('typ', models.CharField(choices=[('einnahme', 'Einnahme'), ('ausgabe', 'Ausgabe')], max_length=8, verbose_name='Art')),
                ('sphaere', models.CharField(choices=[('ideell', 'Ideeller Bereich'), ('vermoegen', 'Vermögensverwaltung'), ('zweck', 'Zweckbetrieb'), ('wirtschaft', 'Wirtschaftlicher Geschäftsbetrieb')], default='ideell', help_text='Zuordnung bitte mit dem Steuerberater/Finanzamt abstimmen', max_length=10, verbose_name='Steuerliche Sphäre')),
                ('sortierung', models.PositiveIntegerField(default=100, verbose_name='Sortierung')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Buchungskategorie',
                'verbose_name_plural': 'Buchungskategorien',
                'ordering': ['typ', 'sphaere', 'sortierung', 'name'],
                'unique_together': {('verein', 'name', 'typ')},
            },
        ),
        migrations.CreateModel(
            name='Kassenbericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(help_text='z. B. Kassenbericht 2026', max_length=150, verbose_name='Titel')),
                ('von', models.DateField(verbose_name='Zeitraum von')),
                ('bis', models.DateField(verbose_name='Zeitraum bis')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('abgeschlossen', 'Abgeschlossen')], default='entwurf', editable=False, max_length=13, verbose_name='Status')),
                ('kassenwart', models.CharField(blank=True, max_length=100, verbose_name='Kassenwart/in')),
                ('pruefer_1', models.CharField(blank=True, max_length=100, verbose_name='Kassenprüfer/in 1')),
                ('pruefer_2', models.CharField(blank=True, max_length=100, verbose_name='Kassenprüfer/in 2')),
                ('kassenbestand_gezaehlt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gezählter Bargeldbestand am Stichtag (€)')),
                ('bankbestand_laut_auszug', models.DecimalField(blank=True, decimal_places=2, help_text='Summe aller Bankkonten laut Auszug', max_digits=12, null=True, verbose_name='Kontostand laut Kontoauszug am Stichtag (€)')),
                ('pruefbemerkung', models.TextField(blank=True, help_text='Wird im Bericht abgedruckt (z. B. Ergebnis der Kassenprüfung, Empfehlung zur Entlastung)', verbose_name='Bemerkungen / Prüfungsergebnis')),
                ('abgeschlossen_am', models.DateField(blank=True, editable=False, null=True, verbose_name='Abgeschlossen am')),
                ('ablage', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.ablagedokument', verbose_name='Ablage')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Kassenbericht',
                'verbose_name_plural': 'Kassenberichte',
                'ordering': ['-bis', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('typ', models.CharField(choices=[('bank', 'Bankkonto'), ('bar', 'Barkasse')], default='bank', max_length=4, verbose_name='Art')),
                ('eroeffnungsbestand', models.DecimalField(decimal_places=2, default=0, help_text='Bestand zum Eröffnungsdatum – Ausgangspunkt aller Berechnungen', max_digits=12, verbose_name='Eröffnungsbestand (€)')),
                ('eroeffnungsdatum', models.DateField(default=datetime.date.today, help_text='Buchungen sind erst ab diesem Datum möglich', verbose_name='Eröffnungsdatum')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Konto',
                'verbose_name_plural': 'Konten',
                'ordering': ['typ', 'name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Buchungsdatum')),
                ('typ', models.CharField(choices=[('einnahme', 'Einnahme'), ('ausgabe', 'Ausgabe')], max_length=8, verbose_name='Art')),
                ('betrag', models.DecimalField(decimal_places=2, help_text='immer positiv erfassen', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Betrag (€)')),
                ('text', models.CharField(max_length=250, verbose_name='Buchungstext')),
                ('belegnummer', models.CharField(blank=True, help_text='Leer lassen = automatisch (B-JJJJ-000001)', max_length=30, verbose_name='Belegnummer')),
                ('beleg', models.FileField(blank=True, upload_to=apps.core.util.upload_pfad, verbose_name='Beleg (Scan/Foto)')),
                ('quelle', models.CharField(choices=[('manuell', 'Manuell erfasst'), ('zahlung', 'Aus Zahlung'), ('spende', 'Aus Spende'), ('aufwand', 'Aus Aufwandsentschädigung'), ('kosten', 'Aus Veranstaltungsbudget')], default='manuell', editable=False, max_length=8, verbose_name='Herkunft')),
                ('quelle_id', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buchungen', to='events.veranstaltung', verbose_name='Veranstaltung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.buchungskategorie', verbose_name='Kategorie')),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.konto', verbose_name='Konto')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Kassenbuch',
                'ordering': ['-datum', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('quelle_id__isnull', False)), fields=('verein', 'quelle', 'quelle_id'), name='buchung_quelle_eindeutig')],
            },
        ),
    ]
