# Generated by Django 6.1.1 on 2026-09-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('documents', '0002_ablagedokument_paperless_fehler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='ablage',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.ablagedokument', verbose_name='Ablage'),
        ),
    ]
