# Generated by Django 6.1.1 on 2026-09-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_buchung_ablage'),
        ('finance', '0006_alter_fintszugang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='fints_zugang',
            field=models.ForeignKey(blank=True, help_text='Nur setzen, wenn dieses Konto automatisch per FinTS abgerufen werden soll (Verwaltung › FinTS-Zugänge) - sonst weiterhin manueller Kontoauszug-Import.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konten', to='finance.fintszugang', verbose_name='FinTS-Zugang'),
        ),
    ]
