# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.util
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('uebergeordnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unterordner', to='documents.ordner', verbose_name='Übergeordneter Ordner')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Ablage-Ordner',
                'verbose_name_plural': 'Ablage-Ordner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ablagedokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('kategorie', models.CharField(choices=[('protokoll', 'Protokoll'), ('einladung', 'Einladung'), ('serienbrief', 'Serienbrief'), ('satzung', 'Satzung & Verträge'), ('beleg', 'Belege'), ('kassenbericht', 'Kassenbericht'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=13, verbose_name='Kategorie')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Datum des Dokuments')),
                ('datei', models.FileField(upload_to=apps.core.util.upload_pfad, verbose_name='Datei')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='Version')),
                ('beschreibung', models.CharField(blank=True, max_length=300, verbose_name='Beschreibung')),
                ('veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ablage', to='events.veranstaltung', verbose_name='Zur Veranstaltung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('ordner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.ordner', verbose_name='Ordner')),
            ],
            options={
                'verbose_name': 'Ablage-Dokument',
                'verbose_name_plural': 'Ablage',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name der Vorlage')),
                ('art', models.CharField(choices=[('einladung', 'Einladung'), ('protokoll', 'Protokoll'), ('serienbrief', 'Serienbrief / Mitgliederinformation'), ('brief', 'Brief'), ('sonstiges', 'Sonstiges')], default='brief', max_length=12, verbose_name='Art')),
                ('betreff', models.CharField(blank=True, max_length=250, verbose_name='Betreff / Titel')),
                ('text', models.TextField(help_text="Absätze durch Leerzeile trennen. Platzhalter wie {vorname} siehe Seite 'Platzhalter-Hilfe'.", verbose_name='Text')),
                ('ist_standard', models.BooleanField(default=False, help_text="Wird bei 'Einladung/Protokoll erstellen' in Veranstaltungen verwendet.", verbose_name='Standardvorlage dieser Art')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('hinweis', models.CharField(blank=True, max_length=300, verbose_name='Interner Hinweis')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Vorlage',
                'verbose_name_plural': 'Vorlagen',
                'ordering': ['art', 'name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Serienbrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=200, verbose_name='Bezeichnung (intern)')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Briefdatum')),
                ('betreff', models.CharField(blank=True, max_length=250, verbose_name='Betreff')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('status_filter', models.CharField(choices=[('aktiv', 'Nur aktive Mitglieder'), ('aktiv_ruhend', 'Aktive und ruhende Mitglieder'), ('alle', 'Alle Mitglieder (auch ausgetretene)')], default='aktiv', max_length=14, verbose_name='Empfänger: Status')),
                ('nur_mit_email', models.BooleanField(default=False, verbose_name='Nur Mitglieder mit E-Mail-Adresse')),
                ('versendet_am', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Per E-Mail versendet am')),
                ('versand_info', models.CharField(blank=True, editable=False, max_length=300, verbose_name='Versandergebnis')),
                ('ablage', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.ablagedokument', verbose_name='Zuletzt abgelegt als')),
                ('abteilung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.abteilung', verbose_name='Nur Abteilung')),
                ('funktion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.funktion', verbose_name='Nur Funktion (z. B. Vorstand)')),
                ('mitgliedsart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.mitgliedsart', verbose_name='Nur Mitgliedsart')),
                ('veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serienbriefe', to='events.veranstaltung', verbose_name='Veranstaltung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('vorlage', models.ForeignKey(blank=True, help_text='Beim Anlegen werden Betreff und Text aus der Vorlage übernommen.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.vorlage', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Serienbrief',
                'verbose_name_plural': 'Serienbriefe',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Schriftstueck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(max_length=200, verbose_name='Bezeichnung (intern)')),
                ('art', models.CharField(choices=[('einladung', 'Einladung'), ('protokoll', 'Protokoll'), ('serienbrief', 'Serienbrief / Mitgliederinformation'), ('brief', 'Brief'), ('sonstiges', 'Sonstiges')], default='brief', max_length=12, verbose_name='Art')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('betreff', models.CharField(blank=True, max_length=250, verbose_name='Betreff / Titel')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('final', 'Final')], default='entwurf', max_length=8, verbose_name='Status')),
                ('ablage', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.ablagedokument', verbose_name='Zuletzt abgelegt als')),
                ('mitglied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.mitglied', verbose_name='Empfänger (Mitglied, optional)')),
                ('veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schriftstuecke', to='events.veranstaltung', verbose_name='Veranstaltung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('vorlage', models.ForeignKey(blank=True, help_text='Beim Anlegen werden Betreff und Text aus der Vorlage übernommen.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.vorlage', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Schriftstück',
                'verbose_name_plural': 'Schriftstücke',
                'ordering': ['-datum', '-id'],
            },
        ),
    ]
