# Generated by Django 6.1.1 on 2026-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ablagedokument',
            name='paperless_fehler',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='Letzter Paperless-Fehler'),
        ),
        migrations.AddField(
            model_name='ablagedokument',
            name='paperless_gesendet_am',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='An Paperless gesendet am'),
        ),
        migrations.AddField(
            model_name='ablagedokument',
            name='paperless_task_id',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Paperless-Task-ID'),
        ),
    ]
