# Generated by Django 6.1.1 on 2026-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_ablagedokument_paperless_fehler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ablagedokument',
            name='oeffentlich',
            field=models.BooleanField(default=False, help_text='Ohne Anmeldung für jeden abrufbar (z. B. Datenschutzerklärung, Aufnahmeformular). Nur aktivieren, wenn das Dokument wirklich für die Öffentlichkeit bestimmt ist!', verbose_name='Öffentlich auf der Startseite sichtbar'),
        ),
        migrations.AlterField(
            model_name='ablagedokument',
            name='kategorie',
            field=models.CharField(choices=[('protokoll', 'Protokoll'), ('einladung', 'Einladung'), ('serienbrief', 'Serienbrief'), ('satzung', 'Satzung & Verträge'), ('datenschutz', 'Datenschutzerklärung'), ('formular', 'Formulare'), ('beleg', 'Belege'), ('kassenbericht', 'Kassenbericht'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=13, verbose_name='Kategorie'),
        ),
    ]
