# Generated by Django 6.1.1 on 2026-09-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_ablagedokument_oeffentlich_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorlage',
            name='hinweis',
            field=models.TextField(blank=True, verbose_name='Interner Hinweis'),
        ),
    ]
