# Generated by Django 6.1.1 on 2026-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_vorlage_hinweis_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ablagedokument',
            name='paperless_info',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='Paperless-Hinweis'),
        ),
        migrations.AddField(
            model_name='ablagedokument',
            name='paperless_pruefsumme',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Prüfsumme der übergebenen Datei'),
        ),
    ]
