# Generated by Django 6.1.1 on 2026-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_paperless_duplikatschutz'),
    ]

    operations = [
        migrations.AddField(
            model_name='ablagedokument',
            name='paperless_status',
            field=models.CharField(blank=True, editable=False, max_length=15, verbose_name='Paperless-Status'),
        ),
        migrations.AddField(
            model_name='ablagedokument',
            name='tags',
            field=models.CharField(blank=True, help_text='Kommagetrennt. Werden bei der Übergabe an Paperless als Tags gesetzt. Leer lassen = Art des Dokuments und Jahr werden automatisch eingetragen.', max_length=300, verbose_name='Tags'),
        ),
    ]
