# Generated by Django 6.1.1 on 2026-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_tags_und_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ablagedokument',
            name='paperless_tags',
            field=models.CharField(blank=True, editable=False, max_length=500, verbose_name='Tags in Paperless (zuletzt übergeben)'),
        ),
    ]
