# Generated by Django 6.1.1 on 2026-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_paperless_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ablagedokument',
            name='dokumenttyp',
            field=models.CharField(blank=True, help_text='Leer lassen = die Art des Dokuments (z. B. Protokoll, Rechnung) wird als Dokumenttyp übergeben.', max_length=150, verbose_name='Dokumenttyp (Paperless)'),
        ),
        migrations.AlterField(
            model_name='ablagedokument',
            name='kategorie',
            field=models.CharField(choices=[('rechnung', 'Rechnung'), ('zuwendung', 'Zuwendungsbestätigung'), ('protokoll', 'Protokoll'), ('einladung', 'Einladung'), ('serienbrief', 'Serienbrief'), ('satzung', 'Satzung & Verträge'), ('datenschutz', 'Datenschutzerklärung'), ('formular', 'Formulare'), ('beleg', 'Belege'), ('kassenbericht', 'Kassenbericht'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=13, verbose_name='Kategorie'),
        ),
    ]
