# Generated by Django 6.1.1 on 2026-09-22 15:16

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_verein_akzentfarbe_fuss'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperlessVerbindung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='z. B. https://paperless.example.org (ohne / am Ende)', verbose_name='Paperless-Adresse')),
                ('api_token', apps.core.fields.VerschluesseltesTextField(blank=True, help_text='Unter Paperless: Mein Profil › API-Token erzeugen', verbose_name='API-Token')),
                ('korrespondent', models.CharField(blank=True, help_text='Wird in Paperless angelegt, falls noch nicht vorhanden. Leer = keiner.', max_length=150, verbose_name='Standard-Korrespondent')),
                ('dokumenttyp', models.CharField(blank=True, help_text='Wird in Paperless angelegt, falls noch nicht vorhanden. Leer = keiner.', max_length=150, verbose_name='Standard-Dokumenttyp')),
                ('tags', models.CharField(blank=True, help_text='Kommagetrennt, z. B. Vereinsverwaltung,Ablage. Werden in Paperless angelegt, falls noch nicht vorhanden.', max_length=300, verbose_name='Standard-Tags')),
                ('tls_pruefen', models.BooleanField(default=True, help_text='Nur zum Testen mit selbstsigniertem Zertifikat abschalten', verbose_name='TLS-Zertifikat prüfen')),
                ('aktiv', models.BooleanField(default=False, verbose_name='Anbindung aktiv')),
                ('letzter_test', models.CharField(blank=True, editable=False, max_length=300, verbose_name='Letzter Verbindungstest')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Paperless-Verbindung',
                'verbose_name_plural': 'Paperless-Verbindungen',
                'constraints': [models.UniqueConstraint(fields=('verein',), name='eine_paperless_verbindung_je_verein')],
            },
        ),
    ]
