# Generated by Django 6.1.1 on 2026-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlessverbindung',
            name='kategorie_tags',
            field=models.BooleanField(default=True, help_text='Jedes Dokument bekommt in Paperless automatisch die Ablage-Kategorie (z. B. Protokoll, Belege) als Tag - zusätzlich zu den Standard-Tags.', verbose_name='Kategorie als Tag setzen'),
        ),
    ]
