# Generated by Django 6.1.1 on 2026-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0002_paperless_duplikatschutz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlessverbindung',
            name='kategorie_tags',
            field=models.BooleanField(default=True, help_text='Gilt für Dokumente ohne eigene Tags (neue Dokumente bekommen Art und Jahr ohnehin als bearbeitbare Tags vorbelegt).', verbose_name='Art und Jahr automatisch als Tag setzen'),
        ),
    ]
