# Generated by Django 6.1.1 on 2026-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0003_tags_und_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlessverbindung',
            name='auto_uebergabe',
            field=models.BooleanField(default=True, help_text='Rechnungen (beim Ausstellen), Zuwendungsbestätigungen, abgeschlossene Kassenberichte, abgelegte Schriftstücke (Status „Final“), Serienbriefe und Belege werden ohne weiteren Klick an Paperless übergeben.', verbose_name='Fertiggestellte Dokumente automatisch übergeben'),
        ),
    ]
