# Generated by Django 6.1.1 on 2026-09-26 12:33

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemeinstellung_update_geprueft_am_and_more'),
        ('members', '0003_vorstand_und_marker'),
        ('paperless', '0004_auto_uebergabe_dokumenttyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlessverbindung',
            name='letzter_abgleich_am',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Letzter Vorstands-Abgleich'),
        ),
        migrations.AddField(
            model_name='paperlessverbindung',
            name='letzter_abgleich_info',
            field=models.TextField(blank=True, editable=False, verbose_name='Ergebnis des letzten Abgleichs'),
        ),
        migrations.AddField(
            model_name='paperlessverbindung',
            name='vorstand_gruppe',
            field=models.CharField(blank=True, default='Vorstand', help_text='Vorstandsmitglieder (Häkchen am Mitglied) werden per „Vorstand abgleichen“ als Paperless-Benutzer angelegt und dieser Gruppe zugeordnet. Die Gruppe wird bei Bedarf mit Leserechten für Dokumente angelegt; weitere Rechte lassen sich in Paperless vergeben.', max_length=150, verbose_name='Paperless-Gruppe für den Vorstand'),
        ),
        migrations.CreateModel(
            name='PaperlessBenutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('paperless_id', models.PositiveIntegerField(verbose_name='Paperless-Benutzer-ID')),
                ('benutzername', models.CharField(max_length=150, verbose_name='Paperless-Benutzername')),
                ('angelegt', models.BooleanField(default=True, help_text='Nur selbst angelegte Konten werden bei Ausscheiden aus dem Vorstand deaktiviert; bereits vorhandene Konten werden lediglich der Gruppe zugeordnet bzw. daraus entfernt.', verbose_name='Vom Abgleich angelegt')),
                ('initialpasswort', apps.core.fields.VerschluesseltesTextField(blank=True, editable=False, verbose_name='Startpasswort')),
                ('mitglied', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paperless_benutzer', to='members.mitglied', verbose_name='Mitglied')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Paperless-Benutzer',
                'verbose_name_plural': 'Paperless-Benutzer',
            },
        ),
    ]
