# Generated by Django 6.1.1 on 2026-10-07 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_altes_rollensystem_abloesen'),
        ('members', '0007_vorstand_funktion_pro_tag'),
        ('paperless', '0005_vorstand_abgleich'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlessbenutzer',
            name='zugang',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperless_benutzer', to='core.zugang', verbose_name='Benutzerzugang (Superadmin ohne Mitgliedsakte)'),
        ),
        migrations.AlterField(
            model_name='paperlessbenutzer',
            name='mitglied',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperless_benutzer', to='members.mitglied', verbose_name='Mitglied'),
        ),
        migrations.AddConstraint(
            model_name='paperlessbenutzer',
            constraint=models.CheckConstraint(condition=models.Q(('mitglied__isnull', False), ('zugang__isnull', False), _connector='OR'), name='paperless_benutzer_mitglied_oder_zugang'),
        ),
        migrations.AddConstraint(
            model_name='paperlessbenutzer',
            constraint=models.CheckConstraint(condition=models.Q(('mitglied__isnull', True), ('zugang__isnull', True), _connector='OR'), name='paperless_benutzer_nicht_beides'),
        ),
    ]
