# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.util
import apps.inventory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gegenstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('inventarnummer', models.CharField(blank=True, help_text='Leer lassen = automatisch (INV-000001)', max_length=20, verbose_name='Inventarnummer')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('hersteller', models.CharField(blank=True, max_length=100, verbose_name='Hersteller')),
                ('modell', models.CharField(blank=True, max_length=100, verbose_name='Modell')),
                ('seriennummer', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('anschaffungsdatum', models.DateField(blank=True, null=True, verbose_name='Anschaffungsdatum')),
                ('anschaffungspreis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Anschaffungspreis (€)')),
                ('aktueller_wert', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aktueller Wert (€)')),
                ('zustand', models.CharField(choices=[('neu', 'Neu'), ('gut', 'Gut'), ('gebrauchsspuren', 'Gebrauchsspuren'), ('defekt', 'Defekt'), ('ausgesondert', 'Ausgesondert')], default='gut', max_length=15, verbose_name='Zustand')),
                ('garantie_bis', models.DateField(blank=True, null=True, verbose_name='Garantie bis')),
                ('verleihbar', models.BooleanField(default=False, verbose_name='Verleihbar')),
                ('leihgebuehr', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Leihgebühr (€)')),
                ('kaution', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Kaution (€)')),
                ('foto', models.ImageField(blank=True, upload_to=apps.core.util.upload_pfad, verbose_name='Foto')),
                ('dokument', models.FileField(blank=True, upload_to=apps.core.util.upload_pfad, verbose_name='Dokument (Rechnung, Handbuch …)')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('verantwortlicher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.mitglied', verbose_name='Verantwortlicher')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Gegenstand',
                'verbose_name_plural': 'Inventar',
                'ordering': ['inventarnummer'],
            },
        ),
        migrations.CreateModel(
            name='Inventur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('jahr', models.PositiveIntegerField(default=apps.inventory.models.aktuelles_jahr, verbose_name='Jahr')),
                ('status', models.CharField(choices=[('laufend', 'Laufend'), ('abgeschlossen', 'Abgeschlossen')], default='laufend', editable=False, max_length=15, verbose_name='Status')),
                ('abgeschlossen_am', models.DateField(blank=True, editable=False, null=True, verbose_name='Abgeschlossen am')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Inventur',
                'verbose_name_plural': 'Inventuren',
                'ordering': ['-jahr', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventurposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('inventarnummer', models.CharField(max_length=20, verbose_name='Inventarnummer')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('standort_text', models.CharField(blank=True, max_length=100, verbose_name='Standort (Soll)')),
                ('ergebnis', models.CharField(choices=[('offen', 'Offen'), ('gefunden', 'Gefunden'), ('nicht_gefunden', 'Nicht gefunden'), ('beschaedigt', 'Beschädigt')], default='offen', max_length=15, verbose_name='Ergebnis')),
                ('notiz', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('gegenstand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.gegenstand', verbose_name='Gegenstand')),
                ('inventur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='inventory.inventur', verbose_name='Inventur')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Inventurposition',
                'verbose_name_plural': 'Inventurpositionen',
                'ordering': ['inventarnummer'],
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Inventar-Kategorie',
                'verbose_name_plural': 'Inventar-Kategorien',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.kategorie', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('beschreibung', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Inventar-Standorte',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.AddField(
            model_name='gegenstand',
            name='standort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.standort', verbose_name='Standort'),
        ),
        migrations.CreateModel(
            name='Verleih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('entleiher_name', models.CharField(blank=True, max_length=150, verbose_name='Entleiher (extern)')),
                ('entleiher_kontakt', models.CharField(blank=True, max_length=200, verbose_name='Kontakt (extern)')),
                ('status', models.CharField(choices=[('reserviert', 'Reserviert'), ('ausgegeben', 'Ausgegeben'), ('zurueckgegeben', 'Zurückgegeben'), ('storniert', 'Storniert')], default='reserviert', max_length=15, verbose_name='Status')),
                ('von', models.DateField(verbose_name='Von')),
                ('bis', models.DateField(verbose_name='Bis (geplante Rückgabe)')),
                ('zweck', models.CharField(blank=True, max_length=200, verbose_name='Zweck')),
                ('leihgebuehr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Leihgebühr (€)')),
                ('kaution', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kaution (€)')),
                ('kaution_zurueckgezahlt', models.BooleanField(default=False, verbose_name='Kaution zurückgezahlt')),
                ('ausgegeben_am', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ausgegeben am')),
                ('ausgegeben_von', models.CharField(blank=True, editable=False, max_length=150, verbose_name='Ausgegeben durch')),
                ('zustand_bei_ausgabe', models.CharField(blank=True, choices=[('neu', 'Neu'), ('gut', 'Gut'), ('gebrauchsspuren', 'Gebrauchsspuren'), ('defekt', 'Defekt'), ('ausgesondert', 'Ausgesondert')], editable=False, max_length=15, verbose_name='Zustand bei Ausgabe')),
                ('zurueckgegeben_am', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zurückgegeben am')),
                ('zustand_bei_rueckgabe', models.CharField(blank=True, choices=[('neu', 'Neu'), ('gut', 'Gut'), ('gebrauchsspuren', 'Gebrauchsspuren'), ('defekt', 'Defekt'), ('ausgesondert', 'Ausgesondert')], editable=False, max_length=15, verbose_name='Zustand bei Rückgabe')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('entleiher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='members.mitglied', verbose_name='Entleiher (Mitglied)')),
                ('gegenstand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verleihe', to='inventory.gegenstand', verbose_name='Gegenstand')),
                ('veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verleihe', to='events.veranstaltung', verbose_name='Für Veranstaltung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Verleih',
                'verbose_name_plural': 'Verleih',
                'ordering': ['-von', '-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gegenstand',
            unique_together={('verein', 'inventarnummer')},
        ),
    ]
