# Generated by Django 6.1.1 on 2026-09-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verleih',
            name='vorgang',
            field=models.UUIDField(blank=True, editable=False, help_text='Gruppiert mehrere gleichzeitig an denselben Entleiher verliehene Gegenstände.', null=True, verbose_name='Vorgang'),
        ),
    ]
