# Generated by Django 6.1.1 on 2026-09-21 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0002_verleih_vorgang'),
    ]

    operations = [
        migrations.AddField(
            model_name='verleih',
            name='rechnung',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verleih_positionen', to='finance.rechnung', verbose_name='Rechnung (Leihgebühr)'),
        ),
    ]
