# Generated by Django 6.1.1 on 2026-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_verleih_rechnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='verleih',
            name='kaution_einbehalten',
            field=models.BooleanField(default=False, editable=False, verbose_name='Kaution einbehalten (auf Rechnung)'),
        ),
    ]
