# Generated by Django 6.1.1 on 2026-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_standort_zu_lagerort_umbenannt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventurposition',
            name='lagerort_ist_text',
            field=models.CharField(blank=True, help_text='Bei der Zählung tatsächlich vorgefundener Lagerort, falls abweichend.', max_length=100, verbose_name='Lagerort (Ist)'),
        ),
    ]
