# Generated by Django 6.1.1 on 2026-10-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventurposition_lagerort_ist_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventurposition',
            name='lagerort_ist_text',
        ),
        migrations.AddField(
            model_name='inventurposition',
            name='lagerort_ist',
            field=models.ForeignKey(blank=True, help_text='Bei der Zählung tatsächlich vorgefundener Lagerort, falls abweichend.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.lagerort', verbose_name='Lagerort (Ist)'),
        ),
    ]
