# Generated by Django 6.1.2 on 2026-10-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_aufgabe_zustaendig_benutzer_alter_aufgabe_zustaendig'),
        ('inventory', '0007_remove_inventurposition_lagerort_ist_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verleih',
            name='aufgabe',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verleih', to='events.aufgabe', verbose_name='Automatisch erzeugte Rückgabe-Aufgabe'),
        ),
    ]
