# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSlidesVerbindung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='z. B. https://versammlung.example.org (ohne / am Ende)', verbose_name='OpenSlides-Adresse')),
                ('benutzername', models.CharField(help_text='OpenSlides-Konto mit der Organisationsrolle „Organisationsverwalter“ (siehe Installationsanleitung)', max_length=150, verbose_name='Technischer Benutzer')),
                ('passwort', apps.core.fields.VerschluesseltesTextField(blank=True, verbose_name='Passwort des technischen Benutzers')),
                ('committee_id', models.PositiveIntegerField(default=1, help_text='In OpenSlides in der Adresszeile: …/committees/<ID>', verbose_name='Ausschuss-ID (Committee)')),
                ('meeting_admin_ids', models.CharField(default='1', help_text='Kommagetrennt, z. B. 1 oder 1,5', max_length=100, verbose_name='Administratoren neuer Versammlungen (OpenSlides-Konto-IDs)')),
                ('sprache', models.CharField(default='de', max_length=5, verbose_name='Sprache neuer Versammlungen')),
                ('tls_pruefen', models.BooleanField(default=True, help_text='Nur zum Testen mit selbstsigniertem Zertifikat abschalten', verbose_name='TLS-Zertifikat prüfen')),
                ('aktiv', models.BooleanField(default=False, verbose_name='Anbindung aktiv')),
                ('letzter_test', models.CharField(blank=True, editable=False, max_length=300, verbose_name='Letzter Verbindungstest')),
                ('letzter_abgleich_am', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Letzter Abgleich')),
                ('letzter_abgleich_info', models.TextField(blank=True, editable=False, verbose_name='Ergebnis des letzten Abgleichs')),
                ('sync_funktion', models.ForeignKey(blank=True, help_text='Leer = alle aktiven Mitglieder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.funktion', verbose_name='Nur Mitglieder mit dieser Funktion abgleichen')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'OpenSlides-Verbindung',
                'verbose_name_plural': 'OpenSlides-Verbindungen',
                'constraints': [models.UniqueConstraint(fields=('verein',), name='eine_openslides_verbindung_je_verein')],
            },
        ),
    ]
