# Generated by Django 6.1.1 on 2026-10-07 20:54

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_altes_rollensystem_abloesen'),
        ('openslides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperadminKonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('openslides_user_id', models.PositiveIntegerField(verbose_name='OpenSlides-Konto-ID')),
                ('openslides_username', models.CharField(max_length=150, verbose_name='OpenSlides-Benutzername')),
                ('openslides_initialpasswort', apps.core.fields.VerschluesseltesTextField(blank=True, editable=False, verbose_name='OpenSlides-Startpasswort')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('zugang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openslides_konto', to='core.zugang', verbose_name='Benutzerzugang')),
            ],
            options={
                'verbose_name': 'OpenSlides-Konto (Superadmin ohne Mitgliedsakte)',
                'verbose_name_plural': 'OpenSlides-Konten (Superadmins ohne Mitgliedsakte)',
            },
        ),
    ]
