# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.util
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufwandsentschaedigung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('art', models.CharField(choices=[('ehrenamtspauschale', 'Ehrenamtspauschale (§ 3 Nr. 26a EStG)'), ('uebungsleiterpauschale', 'Übungsleiterpauschale (§ 3 Nr. 26 EStG)'), ('aufwandsersatz', 'Aufwandsersatz gegen Beleg (Auslagen, Fahrtkosten)'), ('sonstige', 'Sonstige Vergütung')], max_length=25, verbose_name='Art')),
                ('status', models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('ausgezahlt', 'Ausgezahlt'), ('abgelehnt', 'Abgelehnt'), ('verzichtet', 'Verzicht (in Spende umgewandelt)')], default='beantragt', max_length=12, verbose_name='Status')),
                ('datum', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (€)')),
                ('taetigkeit', models.CharField(max_length=250, verbose_name='Tätigkeit / Anlass')),
                ('zeitraum_von', models.DateField(blank=True, null=True, verbose_name='Zeitraum von')),
                ('zeitraum_bis', models.DateField(blank=True, null=True, verbose_name='Zeitraum bis')),
                ('genehmigt_von', models.CharField(blank=True, max_length=100, verbose_name='Genehmigt durch')),
                ('ausgezahlt_am', models.DateField(blank=True, null=True, verbose_name='Ausgezahlt am')),
                ('freibetrag_erklaerung', models.BooleanField(default=False, verbose_name='Empfänger hat erklärt, dass der Freibetrag nicht anderweitig ausgeschöpft ist')),
                ('beleg', models.FileField(blank=True, upload_to=apps.core.util.upload_pfad, verbose_name='Beleg / Abrechnung')),
                ('bemerkung', models.CharField(blank=True, max_length=200, verbose_name='Bemerkung')),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.mitglied', verbose_name='Empfänger')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Aufwandsentschädigung',
                'verbose_name_plural': 'Aufwandsentschädigungen',
                'ordering': ['-datum', '-id'],
            },
        ),
    ]
