# Generated by Django 6.1.2 on 2026-10-09 05:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufwandsentschaedigung',
            name='betrag',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Betrag (€)'),
        ),
    ]
