# Generated by Django 6.1.1 on 2026-09-20 20:15

import apps.core.util
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehrungsart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('beschreibung', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Ehrungsart',
                'verbose_name_plural': 'Ehrungsarten',
                'ordering': ['name'],
                'unique_together': {('verein', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ehrung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('datum', models.DateField(verbose_name='Datum')),
                ('anlass', models.CharField(blank=True, max_length=200, verbose_name='Anlass')),
                ('verliehen_durch', models.CharField(blank=True, max_length=100, verbose_name='Verliehen durch')),
                ('urkunde', models.FileField(blank=True, upload_to=apps.core.util.upload_pfad, verbose_name='Urkunde / Dokument')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.mitglied', verbose_name='Mitglied')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='honors.ehrungsart', verbose_name='Ehrung')),
            ],
            options={
                'verbose_name': 'Ehrung',
                'verbose_name_plural': 'Ehrungen',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Jubilaeumsregel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('jahre', models.PositiveIntegerField(verbose_name='Jahre Mitgliedschaft')),
                ('bezeichnung', models.CharField(blank=True, max_length=100, verbose_name='Bezeichnung')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('verein', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.verein')),
            ],
            options={
                'verbose_name': 'Jubiläumsregel',
                'verbose_name_plural': 'Jubiläumsregeln',
                'ordering': ['jahre'],
                'unique_together': {('verein', 'jahre')},
            },
        ),
    ]
